Repository boring-km/nkrv_bible, pull requests merged in 2021-10, with the labels that each got.

#13 [NB-05] 스플래쉬 스크린
  .gitignore
  android/.gitignore
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  assets/icon/icon_bible.png
  assets/icon/icon_email.png
  assets/icon/icon_facebook.png
  assets/icon/icon_google.png
  assets/icon/icon_guest.png
  assets/icon/icon_kakao.png
  assets/icon/icon_naver.png
  ios/.gitignore
  lib/app.dart
  lib/main.dart
  lib/screen/intro_screen.dart
  lib/screen/login_screen.dart
  lib/screen/main_screen.dart
  lib/screen/splash_screen.dart
  pubspec.yaml
Labels: 새로운 화면 개발, NB-05

#14 [fix] 로그인 화면 이슈 해결
  android/.gitignore
  ios/.gitignore
  lib/screen/intro_screen.dart
  lib/screen/login_screen.dart
  lib/screen/main_screen.dart
  lib/screen/splash_screen.dart
Labels: Fix, NB-05

#16 [NB-07] 음절로 성경 검색
  lib/screen/book_select_screen.dart
Labels: NB-07
